# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:B4J1miFFP7ip5/90CIevjldayGtF1rD0oYtc+Y0Q8hIGyj6YnWkCS6O+RUquKb33Cpti5yrGgJSgvmaA/J+yrHaYiJa4L6UbiJ/JJNBK5XYgOxId2YFhPqUp3wnSG4iM4S6813Dyc92F6pTuSncBLLHZ+qeZsCq8H6VF1dTBIJVvWlwUIxoqkHgVVmPtuwgPsVvX3HpZY4YI7AP8Bfyq/GtzKwuc5PbZe+HXtPhh4g==,iv:aNeM4084La7O6XBj1dY5G1xWuxEsE1uCte2F+xAXY5A=,tag:266hdWzKseq6cdKkRL4dwg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1p0hedfsltseczmgl4snz9084jdme3jfudjh5004nt2v8e3f0g3ssxypgm4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxU0xKa2Rzc3lwWkRmVkFp
        cXBEa2xvUmFwTnJnWFJpUm9BN01pbGcxTWh3CnVMaThpSFpIZXZYRStPK2RORmF2
        K09YZStZbVJSUlF4N2pPN1o1YnpheFEKLS0tIDF4cFQ4b3BDS044OVpGQUZqeHl0
        bkxxMHA4U0hwdTM1eEd5Q2QxSzhiQTAK87ukRgt3opyjkG/+gHgo9wLsOlHOlScu
        y97PVb88/QCH2WP0nV0uNoNROYTgAD9FsYufZVaZfRmWX6gTVB4rVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-01T03:26:35Z"
  mac: ENC[AES256_GCM,data:JS1M4+6mlfZUK2xfX8nZGwdUdOdZLIuzwJlp0K2ZhR4QNVYSym/tpv6OF7oxPsQzjOi/C54yCtlrIDXT1eUA68AhiCqS99qA6gVyFOGRHVUH7DDSmEE9b9j+ghfdy3ytYm+Uhk5LnG/mHfqVdzng0vJZ0EYtLPevEKBzTTBqBlw=,iv:QDACxoP8x8mDZL7f0mR3/RDtlZ+uC7vq131t9yu/jis=,tag:COYkaOou6QRJsBH8qLnvPA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
