---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1p0hedfsltseczmgl4snz9084jdme3jfudjh5004nt2v8e3f0g3ssxypgm4"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1p0hedfsltseczmgl4snz9084jdme3jfudjh5004nt2v8e3f0g3ssxypgm4"
stores:
  yaml:
    indent: 2
