# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:fLqjyReVZHGbk+dBbWmZY5LuzzC6uZ0hevfY+652Vz6KKLb4JtbFeg==,iv:u+lHOzXkAnuNzLSIxfPDwbE/6DMdHnd9j4GiL03CD4w=,tag:lNVqy1imHFZoRybSbdYdGg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1p0hedfsltseczmgl4snz9084jdme3jfudjh5004nt2v8e3f0g3ssxypgm4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eEFXRDdBZDRaYmVCMks4
        UStoalpsaW10Vjg1WUJsN3BGNHd2eHVIZG5ZCjUwMlBnRHRhN0wxQW1TT1FMWS9w
        TGtPZ2lDMmZOL2dRckFrUXRpTzJyczQKLS0tIHNKN1hZR0xVdjIvUi9xVDZ1WFZG
        Ulg1Z3BiVWdOVW04YVc0dWRNbkVoRkkKrWdOwR4f/mLwjd56738SKjsGwJ+7FUYU
        wQE2OR3tzeibwbCgAmXIUGToh9ng+s/pcct0trxoVb/kDgVItQmqiw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-01T02:47:00Z"
  mac: ENC[AES256_GCM,data:K/o1YBRlLgapcXtEYN8U5tT8ZULQUx6/AhIprGGlwaT2XrwVHLbobnOtx1ejrjOjqiQnPBGoOSwO4umlnLOpkCqpY6/ZqNrxNqIHRglNiRmEoRc3ecJfQEhTShtXwybwNDIMGCYq98ZeAgERZZjf2nEpR+pl22kGriREi5zlHdQ=,iv:bCPaIe5DwE9+svg8ksjkcRjvzhCFjCPqwDckoUiB6M4=,tag:nxNyzsSq9Ieni2+wXGuwvQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
