---
  # yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
  apiVersion: helm.toolkit.fluxcd.io/v2
  kind: HelmRelease
  metadata:
    name: &app trilium
  spec:
    interval: 5m

    chart:
      spec:
        chart: app-template
        version: 3.7.1
        sourceRef:
          kind: HelmRepository
          name: bjw-s
          namespace: flux-system
    releaseName: trilium
    targetNamespace: default
    maxHistory: 2

    install:
      createNamespace: true
      remediation:
        retries: 3

    upgrade:
      cleanupOnFail: true
      remediation:
        strategy: rollback
        retries: 3

    uninstall:
      keepHistory: false

    values:

      controllers:
        trilium:
          annotations:
            reloader.stakater.com/auto: "true"
          containers:
            *app :
              image:
                repository: triliumnext/notes
                tag: v0.91.6
              env:
                TZ: ${TIMEZONE}
                TRILIUM_DATA_DIR: &datadir /trilium-data
                USER_UID: 1000
                USER_GID: 1000
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
                limits:
                  memory: 2Gi
    # defaultPodOptions:
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 1000
    #     runAsGroup: 1000
    #     fsGroup: 1000
    #     fsGroupChangePolicy: OnRootMismatch
    #     seccompProfile: { type: RuntimeDefault }

      service:
        *app :
          controller: *app
          ports:
            http:
              port: &port 8080

      ingress:
        app:
          enabled: true
          className: external
          annotations:
            external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          hosts:
            - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
              paths:
                - path: /
                  service:
                    identifier: *app
                    port: *port
          tls:
            - hosts:
                - *host
      persistence:
        config:
          enabled: true
          existingClaim: trilium-pvc
          globalMounts:
            - path: *datadir