---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./controlplaneio.yaml
  - ./coredns.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./metrics-server.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./openebs.yaml
  - ./external-secrets.yaml
  - ./one-password.yaml
  - ./actions-runner-controller.yaml
  #- ./prometheus-community.yaml
  #- ./prometheus-operator.yaml
  - ./piraeus.yaml
  - ./gatus.yaml
  #- ./kube-prometheus-stack.yaml
