# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ajoJJJcg0nKXUG/a6K+WGDMtmuWvRDNFfaygB6YngU68J1iyw6Vppg==,iv:hT3vesNbmVeDhhiMDXAi0tOJdQjAnuecbNHAvHEbBNM=,tag:yoy2DLy0BSWTmn7HUoIT9g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1p0hedfsltseczmgl4snz9084jdme3jfudjh5004nt2v8e3f0g3ssxypgm4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOW1WUktqSjU2UmY4REVB
        VklnVUFxaXkwYm5wbVJoc2xFN0dVR09odWpjCnY4bzJaM05VL1pGT0FvbmpaNG93
        VFVOUkFqL1RyZ1QrVm9qRzZFLytWKzgKLS0tIEZWckY5MUZSWXJiTVZZK2hsNG4y
        NGlOcG13TXp1VFJ0MzZHeFVaUmt2UVkKWCDJBhbUwzguZ7e2rGOWcZaOK22TGaL1
        bGxzWWSBBfRNZ4uIJKZBIZNSDk/RLNP+AL/qIB73BJf1X2aoKYhiAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-01T02:47:00Z"
  mac: ENC[AES256_GCM,data:gnT4G86XnR6g29BQZaC/cdfUstdAhxBEQ0hhNV8Qjc12qkgTJcKhheIaA/mtn/cZqertBeunlrBeaT1ccU3/okUyC32NN+rNdDVnBN1fgo6lqJb330gpKDEhsvgiGxdOSnkO1XLoSxbalJI4jrBj6iPxIIzEJMINCuwD1TVyDx8=,iv:bR8qBynGgHzCT5WgouUB66s7uf4QvPonQFjjVSzkZ/Y=,tag:4FMds9CUOcyhE9tUBW/bRw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
