---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
spec:
  interval: 2h
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: uninstall
  uninstall:
    keepHistory: false
  values:
    controllers:
      homepage:
        annotations:
          configmap.reloader.stakater.com/reload: *app
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v0.10.9
            env:
              LOG_TARGETS: stdout
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      *app :
        controller: *app
        ports:
          http:
            port: &port 3000

    ingress:
      app:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: *app
                  port: *port
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
#        type: emptyDir
        existingClaim: homepage-pvc
        globalMounts:
          - path: /app/config
      configs:
        enabled: true
        type: configMap
        name: *app
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
            readOnly: true
          - subPath: docker.yaml
            path: /app/config/docker.yaml
            readOnly: true
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
            readOnly: true
          - subPath: services.yaml
            path: /app/config/services.yaml
            readOnly: true
          - subPath: settings.yaml
            path: /app/config/settings.yaml
            readOnly: true
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
            readOnly: true
    serviceAccount:
      create: true
