---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 8Gi
  storageClassName:  openebs-hostpath
